ansible/ansible-compat

test/test_runtime.py, tox.ini
=> Improve code coverage

src/ansible_compat/runtime.py, test/assets/requirements-invalid-collection.yml, test/assets/requirements-invalid-role.yml, test/test_runtime.py, tox.ini
* improve coverage
* fixed logic bugs found during previous step
=> Refactor install_requirements

src/ansible_compat/config.py
This should enable auto-complete in code editor, making much easier to use Config() class.
=> Document ansible configuration attributes

src/ansible_compat/runtime.py
Offline implementation was already broken as it did apply to only some commands.
Related: https://github.com/ansible-community/molecule/discussions/3198#discussioncomment-1050054
=> Remove offline option

src/ansible_compat/runtime.py, test/test_runtime.py, tox.ini
=> Improve collection upgrade implementation

src/ansible_compat/runtime.py, test/test_runtime.py, tox.ini
=> Improve detection of badly names roles

test/test_runtime.py, tox.ini
=> Improve coverage

src/ansible_compat/runtime.py, test/test_runtime.py
This is is preparatory change for #59 which is also fixing some bugs. There is no behavior change on this refactoring.
=> Make _install_galaxy_role a Runtime method

.pre-commit-config.yaml, src/ansible_compat/runtime.py, test/roles/sample4/meta/main.yml, test/test_runtime.py, tox.ini
Includes workaround for https://github.com/PyCQA/pylint/issues/4667 bug.
=> Fix prepare environment without isolation

src/ansible_compat/runtime.py, test/collections/acme.goodies/roles/baz/molecule/deep_scenario/converge.yml, test/collections/acme.goodies/roles/baz/molecule/deep_scenario/molecule.yml, test/test_runtime.py, test/test_runtime_example.py, tox.ini
- adds install_local parameter to prepare_environment(), defaulting  to False
- install local role or collection only when local_install is enabled
Fixes: #65
=> Add ability to install local collection or role

.github/workflows/tox.yml, .pre-commit-config.yaml, constraints.txt, docs/requirements.txt, setup.cfg, tox.ini
Related: https://github.com/ansible-community/devtools/issues/6
=> Add support for py310

.github/workflows/tox.yml
Related: https://github.com/ansible-community/devtools/wiki/gha
=> Adopt check summary job pattern on GHA

.github/workflows/push.yml, .github/workflows/release.yml, .github/workflows/tox.yml, .pre-commit-config.yaml, docs/index.md, pyproject.toml
Related: https://github.com/ansible-community/devtools/issues/31
=> Adopt prettier

.pre-commit-config.yaml, src/ansible_compat/config.py, src/ansible_compat/loaders.py, src/ansible_compat/prerun.py, src/ansible_compat/runtime.py, test/test_runtime.py
We previously used unreleased version of pylint.
=> Correct pylint version

src/ansible_compat/runtime.py, test/roles/acme.missing_deps/meta/main.yml, test/roles/acme.missing_deps/requirements.yml, test/test_runtime.py, tox.ini
=> Add offline option to prepare_environment

src/ansible_compat/runtime.py
Fixes: https://github.com/ansible/ansible-lint/issues/1712
=> Add support for tower requirements

src/ansible_compat/runtime.py
Fix FileExistsError failure with symlink recreation
=> Prevent occasional FileExistsError with symlink recreation

src/ansible_compat/runtime.py
This should reduce the amount of red-herrings when running our tooling.
Related: https://github.com/paramiko/paramiko/issues/2038
=> Avoid CryptographyDeprecationWarning from paramiko

src/ansible_compat/runtime.py
Related: https://github.com/ansible-collections/community.docker/issues/364#issuecomment-1183059186
=> Allow installation of pre-released collections

src/ansible_compat/runtime.py
Related: https://github.com/ansible/ansible/issues/77762
=> Avoid python warning about unknown warning category

.github/workflows/tox.yml, tox.ini
This should ease debugging failures.
=> Split GHA jobs for old ansible versions

requirements.txt, setup.cfg
=> Add packaging to dependencies

src/ansible_compat/runtime.py
=> Correct offline cli arg support check

.github/release-drafter.yml, .github/workflows/ack.yml, .github/workflows/push.yml, .github/workflows/release.yml, README.md, setup.cfg
=> Update devtools repo url

src/ansible_compat/runtime.py
Related: https://github.com/ansible/ansible-lint/issues/2673
=> Make galaxy installation verbose

.github/workflows/tox.yml
Related: https://github.com/ansible/devtools/issues/87
=> Use dynamic matrix

.github/workflows/tox.yml, .pre-commit-config.yaml, pyproject.toml, src/ansible_compat/runtime.py, test/test_runtime.py, tox.ini
Related: https://github.com/ansible/ansible-lint/issues/2945
Related: https://github.com/ansible/ansible/commit/56d142350d62fb674e1c6874b3ace2cf5cb933a7
=> Address ansible 2.15 compatibility related to AnsibleCollectionConfig

src/ansible_compat/runtime.py
As passing -p (target collection path destination) break ansible-galaxy ability to find existing collection in other location, we avoid it and use the environment variable approach instead.
Related: https://github.com/ansible/ansible-lint/issues/3251
=> Avoid using -p option with ansible-galaxy install

README.md
=> Correct documentation links

src/ansible_compat/runtime.py
Replace ansible `Display().warning()` method to avoid using stdout for output. Instead we make use of warnings module, as we can easily capture and filter them from consumers, like ansible-lint.
=> Monkeypatch ansible core Display.warning

.pre-commit-config.yaml, src/ansible_compat/runtime.py
=> Include original message in AnsibleWarning

.pre-commit-config.yaml, .vscode/settings.json, pyproject.toml, src/ansible_compat/constants.py, src/ansible_compat/runtime.py, test/collections/acme.goodies/galaxy.yml, test/test_runtime.py
- Install requirements from galaxy files
- Adds a collections dictionary that keeps track of installed collections
=> Also install requirements from galaxy.yml files

src/ansible_compat/runtime.py
Fixes: https://github.com/ansible/ansible-lint/issues/3522
Fixes: https://github.com/ansible/ansible-compat/issues/286
=> Avoid stdout pollution cause by ansible logging

src/ansible_compat/runtime.py, test/test_runtime.py
Reverts ansible/ansible-compat#297
=> Revert "Fix find roles inside collection repository"

src/ansible_compat/constants.py, src/ansible_compat/runtime.py
Related to https://github.com/ansible-community/molecule/issues/3849
Reference: https://github.com/ansible/ansible/pull/46505
=> Support meta main yaml extension

test/test_runtime.py
Related: https://github.com/ansible/ansible/issues/79767
Related: https://github.com/ansible/ansible/issues/81163
=> Adapt collection install test to pass with ansible-core 2.15.3 changes

src/ansible_compat/runtime.py
This is a refactoring that will make it easier to test. There was
no reason for making this part of the class.
=> Make search_galaxy_paths a standalone function

pyproject.toml, src/ansible_compat/runtime.py, test/collections/acme.goodies/galaxy.yml, test/test_runtime.py, tox.ini
Fixes: https://github.com/ansible/ansible-lint/issues/3673
=> Allow git dependencies in galaxy.yml files

.github/workflows/tox.yml, pyproject.toml
Related: https://github.com/ansible/devtools/issues/143
Related: https://github.com/ansible/ansible/issues/81906
=> Add support for python 3.12

.github/release-drafter.yml, pyproject.toml, requirements.txt
=> Update test dependencies

.github/workflows/tox.yml
Related: https://github.com/codecov/feedback/issues/269
=> Fail job if codecov reports a regression

.github/workflows/release.yml, .github/workflows/tox.yml, .pre-commit-config.yaml
Committed via https://github.com/asottile/all-repos
=> Use python3 executable

.packit.yaml, tools/update-spec.sh, tools/update-version.sh
- update the changelog
- Enable notifications
=> Test changelog on rpm

src/ansible_compat/runtime.py
Taking a much safer approach to #387
=> Allow the caller to set the ANSIBLE_COLLECTIONS_PATH

src/ansible_compat/runtime.py
Related: https://github.com/ansible/ansible-lint/issues/4219
=> Avoid duplicate paths when path injection

.github/dependabot.yml
This should sort issue as apparently it did refuse the update the deps with current config.
=> Tune dependabot config

.github/ISSUE_TEMPLATE/bug_report.md, tox.ini
=> Exclude pip check command for docs in tox.ini file

src/ansible_compat/runtime.py
=> Use correct init_plugin_loader

src/ansible_compat/runtime.py, test/test_runtime.py
=> Patch #449 to use ANSIBLE_COLLECTIONS_PATH
