src/ansible_compat/prerun.py, test/test_prerun.py
- change implementation to raise KeyError by default for missing keys
- allow setting a default value, including None
- this would count as major change but because we do not have any release, it should only worth mentioning that in order to keep old behavior user would have to call it with `default=None`.
Follow-Up: https://github.com/ansible-community/ansible-compat/pull/5#discussion_r659281990
=> Make ansible_config_get raise an error when configuration item is missing

.pre-commit-config.yaml, .pylintrc, README.md, setup.cfg, src/ansible_compat/config.py, test/test_config.py, tox.ini
This enables easy access to Ansible configuration.
=> Add class for accessing Ansible configuration

src/ansible_compat/config.py, src/ansible_compat/errors.py, src/ansible_compat/prerun.py, test/test_prerun.py
Fatal errors now raise as exceptions instead of using sys.exit(). This should make it much easier to reuse code.
=> Replace sys.exit with exceptions

.pre-commit-config.yaml, .pylintrc, README.md, constraints.txt, pyproject.toml, setup.cfg, src/ansible_compat/errors.py, src/ansible_compat/prerun.py, src/ansible_compat/runtime.py, test/test_runtime.py, tox.ini
Initial feedback should answer:
* Is `Runtime()` class ok or you have a better proposal?
* Does the README example look at simple a possible to use?
* Runtime construction accepts two optional arguments
* project_dir, defaulting to cwd
* isolated bool, which determine if we should make use of our isolated cache for for installing roles or collections
While current minimal implementation only calls ansible from command line, it will be possible to use the same interface to run ansible execution environments in the future.
=> Add runtime manager class

src/ansible_compat/runtime.py, test/test_runtime.py
This change should ensure that the folders we add to ansible
include paths are listed before others, or the isolation would not
happen.
Also fixes issue where these paths were not added if they did not
already exist inside cache dir. That is problematic as they
are likely to created after Runtime is initialized.
=> Ensure custom paths are injected before other paths

src/ansible_compat/runtime.py, test/test_runtime.py, tox.ini
This will allow us to remove the old `prerun.check_ansible_presence` implementation and make instantiation quite nice an easy.
Also this approach is compatible with a possible future use of ansible-runner.
Partial-Fix: #6
=> Add ability to check minimal ansible version

README.md, docs/examples.md, docs/index.md, test/test_configuration_example.py, test/test_runtime_example.py
- move examples into standalone file which is included in builded doc
- put link from project readme to documentation site
- include few basic badges in project readme
=> Reorganize documentation

src/ansible_compat/constants.py, src/ansible_compat/runtime.py, test/roles/acme.sample2/meta/main.yml, test/roles/ansible-role-sample/meta/main.yml, test/roles/sample3/meta/main.yml, test/test_runtime.py, tox.ini
- Fixes a bug introduce when we added support for project_dir and we still continued to rely on CWD in few places.
- Adds tests for covering this use-case
=> Fix standalone role bootstrapping

.pre-commit-config.yaml, .pylintrc
Remove integration of pylint-pytest as it seems to not produce very reliable results both locally on on CI. Even worse the way F6401 because it only confuses the user, making much harder to identify what was the root cause.
One practical example is the output seen on https://github.com/ansible-community/ansible-compat/pull/32/checks?check_run_id=3161131064
Related: https://github.com/reverbc/pylint-pytest/issues/21
=> Drop use of pylint-pytest

src/ansible_compat/config.py, src/ansible_compat/runtime.py, test/test_config.py, test/test_runtime.py
Replace previous double directional use of aliases for renamed options, raise warnings when deprecated names are used.
=> Ensure we encourage consistent use of config values

codecov.yml
- remove path report, we care only about whole project coverage
- configure threshold to 0.5% which should be small enough to hide
rounding errors while not allowing regression in coverage.
=> Tune codecov reports

pyproject.toml, src/ansible_compat/config.py, test/test_config.py
It seems that our attempt to recommend use of specific
names does trigger runtime warnings from within the library itself,
risking to confuse users.
=> Remove deprecation warnings

.github/workflows/tox.yml, tox.ini
Assures we list version of ansible used by each tox environment.
This makes it move explicit and easier to identify bugs.
=> chore: clarify versions of ansible used during testing

src/ansible_compat/config.py
While this was not directly used, it makes no sense to keep the wrong default value inside.
=> Fix default value for roles path

src/ansible_compat/config.py, test/test_config.py, test/test_runtime.py, tox.ini
Fixes regression that happened with retrieval of configuration when we added default class attributes, so we would be able to benefit from editing hints.
We must use `__getattribute__` instead of `__getattr__` because the former one would just return our  class attributes instead of our real configuration from data dictionary.
Also adds one test that would have being failing before this bugfix.
=> Fix config defaults

src/ansible_compat/runtime.py, test/test_runtime.py, tox.ini
Adds a new API method that can easily be used to detect if ansible is within a specified range. That should cover the most common use case of Ansible version checking.
That was found as needed as we found a big number of places where we do the same checks and an extra benefit is that
the user will no longer have to import Version from packaging in order to make the version comparable.
=> Add version_in_range method to Runtime

.pre-commit-config.yaml, pyproject.toml, setup.cfg, setup.py
Also fixing bug uncovered by 6.3.0 related to us missing to mention toml extra in one place.
Related: https://github.com/psf/black/pull/2475#issuecomment-912730714
=> Bump setuptools-scm version

.pre-commit-config.yaml, test/test_config.py, test/test_runtime_example.py
- change test method name to make it more explicit
- ensure caching does not affect testing of ansible_version
- remove empty galaxy.yml file from repository root (repo is not a broken collection)
- moved pip-compile hooks at the end to speedup pre-commit execution
=> Minor test improvements

src/ansible_compat/runtime.py, test/test_runtime.py
From now on, Runtime() will make a copy of os.environ and use that
instead, eventually making required modifications to it. This ensures
that modifications made by our runtime will not affect current
interpreter environment.
This sorts a bug observed during testing where modification to
os.environ started to cross-contaminate between tests.
Another benefit from this change is that it makes easier to adopt use
of containerized/remote ansible runtimes like execution engine. This
change should be considered major because it means that any consumer
of the library must use of `Runtime.exec()` to execute commands
using the modified environment. If they used subprocess.run or similar
they will need at least to pass Runtime.environ in order to avoid
execution errors as os.environ is no longer …
=> Avoid use direct use of os.environ

.github/workflows/tox.yml
Instead of stopping execution of first failure, we run all
ansible tests before failing. This should give better errors as
you could spot if only a particular ansible version is affected.
Disable fail-fast for ansible testing so we can identify if
a particular python version is the only one affected.
Run unit testing only when linting is passing, saving resources as
linters is likely to fail often and is quite fast to run.
=> Improve github actions

.github/workflows/tox.yml
It seems that this change produced opposite effects than intended as it made harder to spot the failed test on test failures.
Reverts ansible-community/ansible-compat#72
=> Revert "Improve github actions"

.pre-commit-config.yaml, constraints.txt, docs/requirements.txt, setup.cfg, src/ansible_compat/runtime.py, test/test_runtime.py, tox.ini
This is a required feature for use within molecule as the executed
commands may run for a long period of time and users want to see
live progress.
Fixes: #40
=> Add ability to execute commands in tee mode

.github/workflows/tox.yml, tox.ini
As ansible dropped support for python below 3.8 on devel branch,
we need to avoid testing it on older pythons.
=> chore: avoid ansible devel on unsupported platforms

.pre-commit-config.yaml, src/ansible_compat/ports.py
- Disable steps not compatible with pre-commit.ci when under it (our own GHA job still runs it)
- alters its update message and update schedule
This will ease reviews by auto-fixing simple linting errors.
=> chore: fix pre-commit.ci

docs/conf.py, docs/requirements.in, docs/requirements.txt
- preparing for adding support for py3.10, as we will need sphinx 4.2.0 or newer.
- fix broken docs jobs due to incorrect URL
~Related: https://github.com/pypa/packaging.python.org/issues/995~
Related: https://github.com/ansible-community/devtools/issues/6
=> chore: update sphinx

tox.ini
Implements workaround for tox bug with usedevelop by relying on pip own
editable option.
Related: https://github.com/tox-dev/tox/issues/2197
=> Avoid tox usedevelop

.github/workflows/release.yml
Apparently create>tags event did not trigger the release workflow,
so we use the setup from molecule project, where it seems to be
working with release>published.
=> Fix GHA release trigger

.github/workflows/tox.yml, mypy.ini, setup.cfg, src/ansible_compat/config.py, tox.ini
Related: https://github.com/ansible-community/molecule/pull/3436
Related: https://github.com/ansible-community/ansible-lint/pull/1850
Note: that there is one lint job failing that we resolve in follow-up because it requires upgrade of pip-tools, and we cannot do that before dropping support for old pythons.
=> Drop support for py36 and py37

.github/workflows/tox.yml, tox.ini
It should be noted that we still test with `2.9` and `devel`.
=> Replace testing with ansible 2.10/2.11 with 2.12

src/ansible_compat/loaders.py, src/ansible_compat/runtime.py, test/test_runtime.py
=> Avoid galaxy install failure with already symlinked collections

.pre-commit-config.yaml, src/ansible_compat/runtime.py, test/test_runtime.py
Fixes: https://github.com/ansible/ansible-lint/issues/2646
Fixes: https://github.com/ansible/ansible-lint/issues/2645
=> Avoid running galaxy on offline mode

docs/conf.py, requirements.txt, setup.cfg
We also drop pytest-markdown due to lack of maintenance.
Related: https://github.com/Jc2k/pytest-markdown/issues/10
=> Bump test deps

pyproject.toml
pyproject.toml:
Update build-system dependency for setuptools-scm to >= 7.0.0, which obsoletes setuptools-scm-git-archive.
Remove wheel as it is not required in a PEP517 build environment facilitating pypa/build and pypa/installer.
=> Update build-system dependency for setuptools-scm to >= 7.0.0

.pre-commit-config.yaml, src/ansible_compat/runtime.py, test/test_runtime.py
This reverts commit 58a50370726bb05469f17ee745403b070e57b53e.
As ansible-galaxy new `--offline` option does not have any practical use for people using requirement files, it means that compat should not have special treatment for it.
Related: https://github.com/ansible/ansible-lint/issues/2729
Related: https://github.com/ansible/ansible-lint/issues/2651
Related: https://github.com/ansible/ansible-lint/issues/2683
=> Revert "Avoid running galaxy on offline mode (#180)"

src/ansible_compat/runtime.py, test/test_runtime.py
We bring back old behavior of offline more as the new one did not work as intended and was not full offline either.
Related: https://github.com/ansible/ansible-lint/issues/2796
=> Restore offline more functionality

README.md
This has dropped everything before 2.12
=> Update README.md for 3.0.0 release

src/ansible_compat/runtime.py
- Ensure the cache dir is added to the collection loader path, in order to allow linting a collection role against a module this collection is providing
- Add missing default collection path to the loader for ansible version prior 2.15.0.dev0, as done by ansible's _configure_collection_loader(). The only remaining difference is the missing handling of COLLECTIONS_SCAN_SYS_PATH.
See https://github.com/ansible/ansible-lint/issues/2969 for reference.
Signed-off-by: Arnaud Patard <apatard@hupstream.com>
=> src/ansible_compat/runtime.py: Fix collection loading

src/ansible_compat/runtime.py, tox.ini
As passing -p (target collection path destination) break ansible-galaxy
ability to find existing collection in other location, we avoid it
and use the environment variable approach instead.
Related: https://github.com/ansible/ansible-lint/issues/3251
=> Change install_collection to avoid use of -p

pyproject.toml, src/ansible_compat/runtime.py
Explanation: https://ivergara.github.io/boolean-arguments-to-functions-in-python.html
This is marked as major because it might request consumers to make small updates if they did not mention the keyword when calling our API.
=> ruff: Make optional arguments keyword-only

src/ansible_compat/config.py
Fixes: https://github.com/ansible/ansible-lint/issues/3344
=> Revert to previous behavior for ansible_collections_path

src/ansible_compat/runtime.py, test/collections/acme.goodies/galaxy.yml, test/test_runtime.py
Related: https://github.com/ansible/ansible-lint/issues/2924
=> Allow use of * version on dependencies

examples/reqs_broken/requirements.yml, src/ansible_compat/constants.py, src/ansible_compat/runtime.py, test/test_runtime.py, tox.ini
Gives explicit error message about invalid requirements.yml files, especially as an unsupported format was used during the 2020 split.
Closes: #274
Related: https://github.com/ansible-community/community-topics/issues/230
=> Improve requirements.yml detection

.gitignore, .vscode/settings.json, ansible.cfg, pyproject.toml, src/ansible_compat/runtime.py, test/test_runtime.py, tox.ini
Related: https://github.com/ansible/ansible-lint/issues/3481
=> Enable access to available plugins

.gitignore, .packit.yaml, .pre-commit-config.yaml, dist/.gitignore, dist/python-ansible-compat.spec.in, tools/get-version.sh, tools/update-version.sh, tox.ini
=> Enable packit rpm packaging

src/ansible_compat/runtime.py, test/test_runtime.py
Reverts ansible/ansible-compat#307
The original revert was not needed because the new behavior was correct. We only had to correct the test suite of ansible-lint to avoid failures. See https://github.com/ansible/ansible-lint/pull/3654
=> Revert "Revert "Fix find roles inside collection repository""

.github/workflows/tox.yml, tox.ini
Adds a pipeline that checks ansible-lint test results with current version of ansible-compat.
Still expected to fail until we sort all the problems it uncovered.
=> Add smoke testing with ansible-lint

src/ansible_compat/runtime.py, test/test_runtime.py, tox.ini
Related: https://github.com/ansible/molecule/issues/4017
If not isolated and COLLECTION_SCAN_SYS_PATH is true, add the sys.paths to collection paths.
This is intended to mimic the functionality of the [collection loader](https://github.com/ansible/ansible/blob/9afaf2216b0bf38cfbd9a0c93409959f78d01820/lib/ansible/utils/collection_loader/_collection_finder.py#L254)
=> Add `sys.path` to collection paths

src/ansible_compat/runtime.py, test/conftest.py, test/test_runtime.py, test/test_runtime_scan_path.py
Revises #318 
This test may seem a little expensive, but rather than modify the current runtime enviroment for pytest by installing the collection into one of the current paths, install the collection into a module scoped virtual enviromnet site packages directory.
This will avoid a conflict with a test that is being simultaniously run because the venv is scoped to the module.
The test was moved into it's own file to reflect the scope of the venv fixture and avoid conflict in the future with other tests that may use it.
The return value of `require_collection` was also modified to provide the version and location of the collection found so it could be used within the test.
=> Revise site packages collection search test

examples/reqs_v2/requirements.yml, src/ansible_compat/runtime.py
Related: https://github.com/ansible/ansible-lint/issues/3686
Related: https://github.com/ansible/ansible/issues/79109
Related: https://github.com/ansible/ansible/pull/81606
=> Automatically add --pre when installing collections from git repositories

src/ansible_compat/runtime.py
A file with just `collections:` in it leads to `{'collections':None}` which makes the loop sad.  Easier to catch it here.
Fixes #4034
=> Catch empty collection lists

pyproject.toml, src/ansible_compat/runtime.py, test/test_runtime_scan_path.py, tox.ini
This PR validates the usage of `isolated` while adding sys.path to collections path.
Closes: https://github.com/ansible/ansible-compat/issues/324
=> Remove isolated option while adding sys.path

src/ansible_compat/runtime.py
This amends ansible/ansible-lint#3962
=> Allow dashes in role namespaces

src/ansible_compat/runtime.py, test/test_runtime.py, tox.ini
Add functionality for detecting if Ansible can find specific playbooks, caching the results. This is useful as they can reside inside collections.
Related: https://github.com/ansible/ansible-lint/pull/4141
=> Add has_playbook method to Runtime

src/ansible_compat/runtime.py
An issue was found with molecule during testing where the collection path was set to the ephemeral directory, an env properly constructed, but then compat nuked the COLLECTION_PATH from the env var.
I think we can assume the caller here has properly constructed the path they wish to use, if not fall back to the previous default
=> Don't nuke the collections path

.pre-commit-config.yaml, src/ansible_compat/config.py, src/ansible_compat/runtime.py, test/test_runtime.py
- Upgrade ruff version for precommit
- Minor change to improve code readibility
=> Minor code quality improvements

src/ansible_compat/config.py, src/ansible_compat/errors.py, src/ansible_compat/loaders.py, src/ansible_compat/runtime.py, src/ansible_compat/schema.py
This used to be done automatically, but they are no longer being skipped on codecov
=> Skip coverage for `if TYPE_CHECKING` blocks

.pre-commit-config.yaml, src/ansible_compat/constants.py, src/ansible_compat/schema.py, test/assets/validate0_expected.json
- Update pre-commit hook to replace yanked types-pkg-resources with types-setuptools
- All versions of types-pkg_resources have been marked as yanked. Updated the dependency to types-setuptools as specified on PyPI (https://pypi.org/project/types-pkg-resources/). This ensures compatibility and resolves the package installation error.  And it solves the issue during the "[pre-commit.ci](http://pre-commit.ci/) - pr — error during build" check (https://github.com/ansible/ansible-compat/pull/397), specifically related to the types-pkg_resources package.
=> Updated Dependency : types-pkg-resources to types-setuptools

src/ansible_compat/constants.py
"Fixes: https://github.com/ansible/ansible-compat/issues/396"
This pull request updates outdated and non-functional links in the `constants.py` file of the `ansible-combat` project. The affected sections include `namespaces` and `roles`.
- Replaced outdated links in the `namespaces` section with updated, functional links.
- Updated broken links in the `roles` section to point to current, valid resources.
- The `constants.py` file now contains valid URLs that are relevant and accessible.
- No functional code changes have been made; only link updates were performed to ensure resource availability.
=> Updated dead links in constants.py

src/ansible_compat/runtime.py
When multiple versions of a collection are installed it is not currently clear where the other version is, this patch gives a bit more detail
Before...
WARNING  Multiple versions of 'ansible.posix' were found installed, only the first one will be used, 1.5.1 (/home/blah/.ansible/collections/ansible_collections).
After...
WARNING  Another version of 'ansible.posix' 1.5.4 was found installed in /home/blah/yard/systems/.venv/lib/python3.11/site-packages/ansible_collections, only the first one will be used, 1.5.1 (/home/blah/.ansible/collections/ansible_collections).
=> provide more detail on multile collection installs

.github/workflows/tox.yml, src/ansible_compat/runtime.py, test/test_runtime.py
=> Re-init plugin loader after collections installation (#411)

.config/requirements-test.in, .github/workflows/tox.yml, pyproject.toml, tox.ini
Related: https://github.com/ansible/team-devtools/issues/229
=> Add support for py313

.config/requirements.in, .github/workflows/tox.yml, .readthedocs.yml, README.md, pyproject.toml, src/ansible_compat/constants.py, src/ansible_compat/runtime.py, src/ansible_compat/types.py, test/conftest.py, test/test_config.py, tox.ini
Related: https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html
=> Support ansible 2.18, drop 2.14/2.15 and py39

tox.ini
Related: https://github.com/astral-sh/uv/issues/10686
=> Ensure we constrain test dependencies with uv

src/ansible_compat/prerun.py, test/test_prerun.py
Fixes: https://github.com/ansible/ansible-lint/issues/4497
=> Ensure that cache directory is writable

src/ansible_compat/runtime.py
Fix the language in info message about patching collection paths.
Simple two letter fix.
=> Fix grammatical error in collection path info message

.packit.yaml
As https://github.com/packit/packit-service/issues/2006 is not yet available, we can only rely on labels to reduce number of cases where we test RPM building.
=> Reduce number of cases when we test RPM building

.packit.yaml, src/ansible_compat/prerun.py, test/test_prerun.py
Fixes: https://github.com/ansible/ansible-lint/issues/4501
Fixes: #455
=> Avoid get_cache_dir errors with read only virtualenvs

.config/pydoclint-baseline.txt, .pre-commit-config.yaml, src/ansible_compat/runtime.py
=> Make warning signature compatible with ansible core 2.19

.python-version, mise.toml
Due to https://github.com/dependabot/dependabot-core/issues/1455
we are forced to add a `.python-version` file so dependabot will not use unsupported older python when running.
Still, we need to reconfigure `mise` to tell it to ignore this file.
=> Workaround for dependabot improper python version
